Controllers/BmiCalculatorController.cs
using MyHealth.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyHealth.Controllers
{
  
    public class BmiCalculatorController : Controller
    {

        ApplicationDbContext _context;

            public BmiCalculatorController()
            {
                _context = new ApplicationDbContext();
            }
            protected override void Dispose(bool disposing)
            {
                _context.Dispose();
            }
            // GET: BmiCalculator
            [HttpGet]
            public ActionResult Index()
            {
           
            if(System.Web.HttpContext.Current.Session["Id"]==null)
            {
                return RedirectToAction("Login", "Accounts");
            }
            ViewBag.message = System.Web.HttpContext.Current.Session["Id"];
            return View();
            
        }
        public ActionResult Save(BmiCalculator bmiCalculator)
        {
            if (bmiCalculator.Id == 0)
            {
                bmiCalculator.Date = DateTime.Now;
                _context.BmiCalculators.Add(bmiCalculator);
            }

            _context.SaveChanges();
            _context.BmiCalculators.ToList();

            return View("Index");
        }
        public ActionResult Display()
        {
            if (System.Web.HttpContext.Current.Session["Id"] == null)
            {
                return RedirectToAction("Login", "Accounts");
            }

            dynamic mymodel = new ExpandoObject();
            mymodel.Bmi = _context.BmiCalculators.OrderByDescending(m=>m.Id).ToList();
                mymodel.User = _context.Registers.ToList();
                ViewBag.message =Session["Id"];
                return View(mymodel);
            
        }

    }
}
    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
@using Microsoft.AspNet.Identity
<div class="navigation">
    <div class="navbar navbar-default navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container">
            <div class="navbar-header">

                @*<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>*@


            </div>
            @Html.ActionLink("MyBMI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            @*   <div class="collapse navbar-collapse" id="navbarColor02">*@
            <ul class="navbar-nav mr-auto">
                <li class="navbar-brand"> @Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "navbar-brand nav-link" })</li>

                <li class="navbar-brand">@Html.ActionLink("BMI Calculator", "Index", "BmiCalculator", new { area = " " }, new { @class = "navbar-brand nav-link" }) </li>
                <li class="navbar-brand"> @Html.ActionLink("MyHistory", "Display", "BmiCalculator", new { area = "" }, new { @class = "navbar-brand nav-link" })</li>

            </ul>

             @Html.Partial("_LoginPartial")

          @*  @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                {
                    @Html.AntiForgeryToken()

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @if (Session["FirstName"] != null)
                            {<text>
                                    Welcome @(Session["FirstName"].ToString())
                            </text>
                        }
                        </li>
                    </ul>
                    @*  <li>
                        @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" }) </li>
                        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                    

                    @*  <div class="nav navbar-nav navbar-right">
                            if (Session["FirstName"] != null)
                            {<text>
                                Welcome @Session["FirstName"].ToString()
                            </text>
                            }
                        </div>
                    


                }

            }

            else
            {
                <ul class="nav navbar-nav navbar-right">
                @*  <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                <li>@Html.ActionLink("Log in", "Login", "Register", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "navbar-brand nav-link" })</li>
                </ul>
            }
            *@



        </div>
    </div>
</div>