Models/BmiCalculator.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyHealth.Models
{
    public class BmiCalculator
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        [Required]
        public float Height { get; set; }
        [Required]
        public float Weight { get; set; }

        public float Bmi { get; set; }
        public int UserId { get; set; }
    }
}

Controllers/Api/BmiCalculatorController.cs
using AutoMapper;
using MyHealth.Dto;
using MyHealth.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using System.Web.UI.WebControls;

namespace MyHealth.Controllers.Api
{
    public class BmiCalculatorController : ApiController
    {
        private ApplicationDbContext _context;
        public BmiCalculatorController()
        {
            _context = new ApplicationDbContext();
        }
        public IEnumerable<BmiCalculatorDto> GetCustomers()
        {
            return _context.BmiCalculators.ToList().Select(Mapper.Map<BmiCalculator, BmiCalculatorDto>);
        }

        [HttpDelete]
        public void Delete(int id)
        {
            var BmiInDb = _context.BmiCalculators.SingleOrDefault(c => c.Id == id);
            if (BmiInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.BmiCalculators.Remove(BmiInDb);
            _context.SaveChanges();

            //  return Ok();
        }

        [HttpPost]
        public IHttpActionResult Create(BmiCalculatorDto bmiCalculatorDto)
        {
            //  var Session = HttpContext.Current.Session;
            //Console.WriteLine(Session["Id"]);
          
               if(!ModelState.IsValid)
            {
                return RedirectToRoute("BmiCalculator",null);
              
            }
                var bmi = Mapper.Map<BmiCalculatorDto, BmiCalculator>(bmiCalculatorDto);
                bmi.Date = DateTime.Now;
                _context.BmiCalculators.Add(bmi);
                _context.SaveChanges();

                bmiCalculatorDto.Id = bmi.Id;
            
                return Created(new Uri(Request.RequestUri + "/" + bmi.Id), bmiCalculatorDto);
            
        }
    }
}

    

Controllers/BmiCalculatorController.cs
using MyHealth.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyHealth.Controllers
{
  
    public class BmiCalculatorController : Controller
    {

        ApplicationDbContext _context;

            public BmiCalculatorController()
            {
                _context = new ApplicationDbContext();
            }
            protected override void Dispose(bool disposing)
            {
                _context.Dispose();
            }
            // GET: BmiCalculator
            [HttpGet]
            public ActionResult Index()
            {
           
            if(System.Web.HttpContext.Current.Session["Id"]==null)
            {
                return RedirectToAction("Login", "Accounts");
            }
            ViewBag.message = System.Web.HttpContext.Current.Session["Id"];
            return View();
            
        }
        public ActionResult Save(BmiCalculator bmiCalculator)
        {
            if (bmiCalculator.Id == 0)
            {
                bmiCalculator.Date = DateTime.Now;
                _context.BmiCalculators.Add(bmiCalculator);
            }

            _context.SaveChanges();
            _context.BmiCalculators.ToList();

            return View("Index");
        }
        public ActionResult Display()
        {
            if (System.Web.HttpContext.Current.Session["Id"] == null)
            {
                return RedirectToAction("Login", "Accounts");
            }

            dynamic mymodel = new ExpandoObject();
            mymodel.Bmi = _context.BmiCalculators.OrderByDescending(m=>m.Id).ToList();
                mymodel.User = _context.Registers.ToList();
                ViewBag.message =Session["Id"];
                return View(mymodel);
            
        }

    }
}
    

Controllers/HealthTipsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyHealth.Controllers
{
    public class HealthTipsController : Controller
    {
        // GET: HealthTips
        public ActionResult Underweight()
        {
            return View();
        }
        public ActionResult Overweight()
        {
            return View();
        }
    }
}

Views/BmiCalculator/Display.cshtml
@using MyHealth.Models

@model dynamic
@{
    ViewBag.Title = "Display";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>BMI History</h1>
<br />
<h2>@ViewBag.message</h2>
<table id="bmi" class="table table-bordered table-hover">
    <thead class="text-white bg-dark">
        <tr>
            <th>Date</th>
            <th>Height</th>
            <th>Weight</th>
            <th>BMI</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (BmiCalculator bmi in Model.Bmi)
        {
            if (bmi.UserId.ToString().Equals(ViewBag.message.ToString()))
            {
                
            <tr class="table-light">

                <td>@bmi.Date.Date.ToShortDateString()</td>
                <td>@bmi.Height</td>
                <td>@bmi.Weight</td>
                <td>@bmi.Bmi</td>
                <td><button data-customer-id="@bmi.Id" class=" js-delete btn btn-outline-secondary">Delete </button></td>
            </tr>
                }
            }
    </tbody>
</table>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#bmi").on("click", ".js-delete", function () {
                var button = $(this);
               if( confirm("Are you sure to delete this customer?")) {
                  //  if (result) {
                $.ajax({
                    url: "/api/bmicalculator/" + button.attr("data-customer-id"),
                    method: "DELETE",
                    success: function () {
                        button.parents("tr").remove();
                    }

                });

                    }
                });

            });


    </script>
}

Views/BmiCalculator/Index.cshtml
@model MyHealth.Models.BmiCalculator
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 id="userid">@ViewBag.message</h2>
 <h1 class="font-weight-bold">BMI Calculation</h1>               

    <div style="font-size:20px;">

        @using (Html.BeginForm("Index", "BmiCalculator"))             //bmi form
        {
            <br />
            <div class="form-group col-md-3">
                @Html.Label("Height in cm/feet/inch") 
                <select id="htype" class="form-control">
                    <option>cm</option>
                    <option>feet</option>
                    <option>inch</option>
                </select>

            </div>


            <div class="form-group col-md-3">
                @Html.LabelFor(m => m.Height)
                @Html.TextBoxFor(m => m.Height, new { @class = "form-control", @id = "height", @placeholder = "Height in cm", required = "required" })
                @Html.ValidationMessageFor(m=>m.Height,"Hi",new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-3">
                @Html.LabelFor(m => m.Weight)
                @Html.TextBoxFor(m => m.Weight, new { @class = "form-control", @id = "weight", @required = "required" })
                @Html.ValidationMessageFor(m=>m.Weight)
            </div>
            <br />

            <div>
                <input type="button" onclick="calc()" id="button2" class="btn btn-primary js-add" value="Calculate">
            </div>
             <br />

            <p>Your BMI is <span id="bmi"></span></p>
             <p id="bmires"></p>

                                                                                          //health tip recommendations
             <h2 class="text-primary font-weight-bold">Recommendations for you!!!</h2>

            <u>
                @Html.ActionLink("Health tips to gain weight", "Underweight", "HealthTips", " ", new { @class = "text-dark" })<br />
                @Html.ActionLink("How to lose weight naturally?", "Overweight", "HealthTips", "", new { @class = "text-dark" })
            </u>




        }

        @section scripts{
            <script>                                                  //bmi calculation
                function calc() {
                    var htype = document.getElementById("htype").value;
                var height = document.getElementById("height").value;
                 var weight = document.getElementById("weight").value;
                  var height_square = height * height;

                    if (htype == "cm")
                       var res = weight / (height_square * 0.0001);
                        else if (htype == "feet")
                        var res = weight / (height_square * 0.0929);
                    else if (htype == "inch")
                        var res = weight / (height_square * 0.0006);

                document.getElementById("bmi").innerHTML = res.toFixed(1);
                if (res < 18.5)
                    document.getElementById("bmires").innerHTML = "You are underweight";
                // document.getElementById("bmiress").innerHTML=@Html.ActionLink("Health tips to gain weight", "Underweight", "HealthTips", " ", new { @class = "text-dark" })<br />

                else if (res >= 18.5 && res <= 24.9)
                    document.getElementById("bmires").innerHTML = "You are healthy";
                else if (res >= 25.0 && res <= 29.9)
                    document.getElementById("bmires").innerHTML = "You are overweight";
                else if (res >= 30.0)
                    document.getElementById("bmires").innerHTML = "You are obese";

                
            }
              $(document).ready(function () {                        //ajax call
                    $("#button2").click(function () {
                        $.ajax(
                            {
                                url: "/api/bmicalculator",
                                method: "POST",

                                data: { //Passing data
                                    Height: $("#height").val(),
                                    Weight: $("#weight").val(),
                                    Bmi: $("#bmi").html(),
                                    UserId: $("#userid").html()

                                }
                            });

                    });

                });

            </script>
        }
    </div>